# Generated by Django 3.1.2 on 2020-10-10 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bgg_slug', models.IntegerField()),
                ('year_published', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('condition', models.CharField(choices=[('1', 'New'), ('2', 'Like New'), ('3', 'Good'), ('4', 'Fair'), ('5', 'Poor')], default='3', max_length=1)),
                ('comment', models.TextField(max_length=500)),
                ('designer', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
