# Generated by Django 3.1.2 on 2020-10-11 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20201010_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='list_type',
            field=models.CharField(choices=[('O', 'Offer List'), ('W', 'Wish List')], max_length=1, verbose_name='Which list?'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
