# Generated by Django 3.1.2 on 2020-10-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201011_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wish',
        ),
    ]
