# Generated by Django 3.1.2 on 2020-10-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_message_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='content',
            new_name='reply',
        ),
    ]
